### PR TITLE
Update api url

### PR DESCRIPTION
**Pull request by benhutton**
@isaachvazquez this change is necessary for this plugin to keep working. Let me know if you'd like us to take over ownership/maintenance.

### CODE REVIEW

**Comment by isaachvazquez** [comment]
@benhutton Will merge it in now. 👍 Happy to hand over ownership after that.

**Comment by benhutton** [comment]
@isaachvazquez thanks!

**Comment by isaachvazquez** [comment]
@benhutton 
Screenshot 2023-12-11 at 11 28 39 AM

Is there something else you or I need to do to allow this?

**Comment by benhutton** [comment]
@isaachvazquez let me get back to you in a bit

**Comment by benhutton** [comment]
@isaachvazquez it wasn't working because I have a fork already. Let's put it on the @desiringgod account. 

Is there an npm package too?

**Comment by isaachvazquez** [comment]
Screenshot 2023-12-11 at 1 09 04 PM

**Comment by benhutton** [comment]
@isaachvazquez i was afraid of that. I just deleted my fork, so transfer to me and I'll transfer it in. Thanks

**Comment by isaachvazquez** [comment]
👍

**Pull request merged**
